Section "Device"
    Identifier "RP6 GPU"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card0"
    Option "AccelMethod" "glamor"
EndSection

Section "InputClass"
    Identifier "RP6 touchscreen rotation"
    MatchProduct "generic ft5x06"
    MatchIsTouchscreen "on"
    Driver "libinput"
    Option "TransformationMatrix" "0 -1 1 1 0 0 0 0 1"
EndSection
