/* Four-row companion to upstream Simple; no duplicated D-pad/navigation page. */
static struct key keys_special[] = {
  {"1", "!", 1, Code, KEY_1},
  {"2", "@", 1, Code, KEY_2},
  {"3", "#", 1, Code, KEY_3},
  {"4", "$", 1, Code, KEY_4},
  {"5", "%", 1, Code, KEY_5},
  {"6", "^", 1, Code, KEY_6},
  {"7", "&", 1, Code, KEY_7},
  {"8", "*", 1, Code, KEY_8},
  {"9", "(", 1, Code, KEY_9},
  {"0", ")", 1, Code, KEY_0},
  {"", "", 0, EndRow},

  {"[", "{", 1, Code, KEY_LEFTBRACE},
  {"]", "}", 1, Code, KEY_RIGHTBRACE},
  {"\\", "|", 1, Code, KEY_BACKSLASH},
  {"-", "_", 1, Code, KEY_MINUS},
  {"=", "+", 1, Code, KEY_EQUAL},
  {"/", "?", 1, Code, KEY_SLASH},
  {";", ":", 1, Code, KEY_SEMICOLON},
  {"'", "\"", 1, Code, KEY_APOSTROPHE},
  {"`", "~", 1, Code, KEY_GRAVE},
  {"Del", "Del", 1, Code, KEY_DELETE, .scheme = 1},
  {"", "", 0, EndRow},

  {"Shift", "Caps", 1.5, Mod, Shift, .scheme = 1},
  {"@", "@", 1, Code, KEY_2, 0, Shift},
  {"#", "#", 1, Code, KEY_3, 0, Shift},
  {"$", "$", 1, Code, KEY_4, 0, Shift},
  {"%", "%", 1, Code, KEY_5, 0, Shift},
  {"&", "&", 1, Code, KEY_7, 0, Shift},
  {"!", "!", 1, Code, KEY_1, 0, Shift},
  {"?", "?", 1, Code, KEY_SLASH, 0, Shift},
  {"Back", "Back", 1.5, Code, KEY_BACKSPACE, .scheme = 1},
  {"", "", 0, EndRow},

  {"ABC", "ABC", 1, BackLayer, .scheme = 1},
  {"Esc", "Esc", 1, Code, KEY_ESC, .scheme = 1},
  {"Alt", "Alt", 1, Mod, Alt, .scheme = 1},
  {",", "<", 0.75, Code, KEY_COMMA},
  {"Space", "Tab", 3, Code, KEY_SPACE},
  {".", ">", 0.75, Code, KEY_DOT},
  {"Enter", "Enter", 2, Code, KEY_ENTER, .scheme = 1},
  {"", "", 0, Last},
};
