#!/bin/sh

SOURCE='/storage/.local/share/rocknix-xfce/integration/Desktop Mode.sh'
TARGET='/storage/.config/modules/Desktop Mode.sh'
TEMP="${TARGET}.new"

[ -f "${SOURCE}" ] || exit 0
mkdir -p /storage/.config/modules
cp "${SOURCE}" "${TEMP}"
chmod 0755 "${TEMP}"
mv -f "${TEMP}" "${TARGET}"

